[package]
name = "kasa_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
kasa_core = { path = "../kasa_core" }
rand = "0.8.5"

[[bench]]
name = "google_images_layout"
harness = false
