[package]
name = "kasa_bench"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = { workspace = true, features = ["html_reports"] }
kasa_core = { path = "../kasa_core" }
rand = { workspace = true }

[[bench]]
name = "google_images_layout"
harness = false
