[package]
name = "kasa_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
ort = { version = "2.0.0-rc.7", features = [
    "rocm",
    "load-dynamic",
] } # should we build it from source?
ndarray = { version = "0.16.1" }
csv = { version = "1.3.1" }
image = { workspace = true }
